### ISSUE TITLE
Specialthreads autoupdate

### ISSUE THREAD

**Issue by aoi-miko** [kurisaba-dev/kurisaba#41]
Make server automatically update special threads using patterns ("Random thread" in title -> update "random thread" specialthread, "аноничный" in text -> the same, etc)

["бсуждать можно любые темы", "каноничный", "Главное помнить, что", "роме знаете-сами-каких.", "андом тред", "андом-тред"]

**Comment by makise-homura** [comment]
I guess it's not needed anymore. There's still no idea about a principle this mechanism should be built on, so it's likely wontfix.
