### ISSUE TITLE
Файлы, удаляемые модераторами, на самом деле не удалять, а скрывать

### ISSUE THREAD

**Issue by mamoruarai** [kurisaba-dev/kurisaba#58]
Нужно сохранять удаляемые файлы для того, чтобы их можно было восстановить. При этом удалённые файлы не должны быть доступны при штатном обращении. Только администраторы могут читать удалённые файлы – желательно через веб, но если это невозможно, достаточно просто хранить их на сервере, перекрыв к ним всякий веб-доступ.

**Comment by makise-homura** [comment]
- [ ] поэкспериментировать на тредах: 
- [ ] поэкспериментировать на постах: 1506, 1511 восстановить
- [ ] ссылку undelete добавить для постов, а не только для тредов
- [ ] посмотреть, почему админу не видны удалённые файлы

**Comment by makise-homura** [comment]
Тоже сделал.

**Comment by mamoruarai** [comment]
Хорошо. Потенциальное загаживание сервера бесполезными тяжёлыми файлами будем нивелировать модераторской работой.
