### ISSUE TITLE
Заменить стиль по умолчанию на Umnochan, сбросить пользовательские настройки стиля

### ISSUE THREAD

**Issue by mamoruarai** [kurisaba-dev/kurisaba#66]
На такой https://410chan.org/css/umnochan.css или очень похожий (обговорим частно). Сделать так, чтобы все пользователи, в том числе и те, которые заходили на Доброчан раньше, увидели Umnochan. В идеале – только те, кто не менял настройку стиля, но если нереально, то вообще все.

**Comment by makise-homura** [comment]
Пофиксил. Увы, настройка стиля сохраняется не только при его изменении, а при каждой загрузке страницы, так что сброшено у всех.

P.S. Соответствующая кука теперь называется `kustyle2`, кука `kustyle` смысла не имеет.
Возможно, имеет смысл отрефакторить это и перетащить из куки в localStorage, но если и да, то на это предлагаю завести отдельный issue с importance:minor.
