### ISSUE TITLE
Дать модераторам возможность исправлять посты

### ISSUE THREAD

**Issue by mamoruarai** [kurisaba-dev/kurisaba#68]
Все старые версии поста сохранять, чтобы админ мог восстановить.

**Comment by makise-homura** [comment]
Редактирование ещё ладно, можно сделать, а вот как при этом ещё и сохранять все старые версии... Тут прямо очень сильно всё надо будет переписывать.

**Comment by makise-homura** [comment]
Идёт на реконцептуализацию.
