### ISSUE TITLE
Дать администратору возможность помечать любые файлы, треды и посты как недоступные для просмотра в РФ

### ISSUE THREAD

**Issue by mamoruarai** [kurisaba-dev/kurisaba#72]
То есть для пользователей с российскими айпишниками. Вместо таких материалов должна показываться картинка, говорящая о том, что в РФ доступ к материалам запрещён.

**Comment by makise-homura** [comment]
- [ ] реализовать блокировку досок
- [ ] реализовать блокировку постов
- [ ] реализовать блокировку файлов
- [ ] сделать, чтобы админу всегда показывались все доски, файлы и посты
- [ ] в админку в настройку досок добавить опцию блокировки доски
- [ ] в шаблон поста добавить опцию блокировки поста
- [ ] в шаблон поста добавить опцию блокировки файла
- [ ] при изменении настроек блокировки ОП-поста то же самое делать для всех постов треда
- [ ] при попытке отправить пост из страны в тред, где country_restrict запрещает смотреть из этой страны, обламывать отправку

**Comment by makise-homura** [comment]
Seems to be done for now.
