### ISSUE TITLE
Модлог в админпанели с виду пуст, в него не пишется ничего нового

### ISSUE THREAD

**Issue by mamoruarai** [kurisaba-dev/kurisaba#76]
Проблема нова, раньше модлог работал как надо. События, после которого модлог сломался, сказать не могу.

**Comment by makise-homura** [comment]
MySQL при обращении к этой таблице говорил `Table 'modlog' is marked as crashed and should be repaired`. Я прогнал `myisamchk` на ней, всё теперь должно быть нормально.
