### ISSUE TITLE
Создать систему тегирования постов и тредов

### ISSUE THREAD

**Issue by mamoruarai** [kurisaba-dev/kurisaba#83]
Модератор может для любого поста, если это не ОП-пост, на модерируемых им досках назначить или поменять текстовую строчку, в которой через запятую будут теги, отражающие суть этого поста. Строчка приписывается к посту, обозначается особым шрифтом и видима всеми пользователями. Также любому пользователю в любом ОП-посте будет видна строчка, в которой показаны все теги, которыми на данный момент описываются посты этого треда, причём рядом с каждым тегом должно стоять число, показывающее, сколько раз ИТТ применялся этот тег.

**Comment by makise-homura** [comment]
Готово. У модеров теперь есть кнопочка "#", которая позволяет им назначать теги посту. Оп-посту теги назначить нельзя. Если в посте есть теги, то они показываются в заголовке (если это ОП-пост, то он показывает теги всех постов в треде). Теги у поста не обязательно должны быть уникальны - посту можно назначить одинаковый тег несколько раз, чтобы увеличить количество в ОП-посте. Пример треда, где уже есть теги [вот](https://rf.dobrochan.nl/bed/res/1501.html).
